# Generated by Django 3.2.6 on 2022-07-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsaggapp', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='guid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(default='static/imgs/news.jpg'),
        ),
        migrations.AlterField(
            model_name='article',
            name='news_publisher',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(),
        ),
    ]
